In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [6]:
df=pd.read_csv("zoo (1).csv")
df.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1

In [7]:
df


animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
96      wallaby     1         0     0     1         0        0         0   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  class_type  
0          1           1  
1          1           1  
2          0           4  
3          1           1  
4          1           1  
..       ...         ...  
96         1           1  
97         0           6  
98         1           1  
99         0           7  
100        0           2  

[101 rows x 18 columns]

In [8]:
 class_type_output=df["class_type"]
 df=df.drop("class_type", axis=1).drop("animal_name", axis=1)
 print(df)

     hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0           1         1         0     0     4     

In [10]:

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df, class_type_output, test_size=0.20)

In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)
y_prediction = classifier.predict(x_test)
y_prediction

array([2, 4, 2, 1, 2, 6, 4, 2, 2, 1, 2, 1, 1, 2, 1, 1, 5, 1, 7, 6, 2])

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
confusion_matrix(y_test,y_prediction)

array([[7, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1]])

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
confusion_matrix(y_test,y_prediction)

array([[7, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1]])

In [14]:
print(accuracy_score(y_test, y_prediction))

0.9523809523809523


In [15]:
predicted_class = list(y_prediction)
actual_class = list(y_test)
for i in range(len(predicted_class)):
    print("Predicted class =", predicted_class[i],"\tActual class =",actual_class[i])

Predicted class = 2 	Actual class = 2
Predicted class = 4 	Actual class = 4
Predicted class = 2 	Actual class = 2
Predicted class = 1 	Actual class = 1
Predicted class = 2 	Actual class = 2
Predicted class = 6 	Actual class = 7
Predicted class = 4 	Actual class = 4
Predicted class = 2 	Actual class = 2
Predicted class = 2 	Actual class = 2
Predicted class = 1 	Actual class = 1
Predicted class = 2 	Actual class = 2
Predicted class = 1 	Actual class = 1
Predicted class = 1 	Actual class = 1
Predicted class = 2 	Actual class = 2
Predicted class = 1 	Actual class = 1
Predicted class = 1 	Actual class = 1
Predicted class = 5 	Actual class = 5
Predicted class = 1 	Actual class = 1
Predicted class = 7 	Actual class = 7
Predicted class = 6 	Actual class = 6
Predicted class = 2 	Actual class = 2
